apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: australia-southeast2-docker.pkg.dev/sit323-24t1-edwards-7b61d76/sit323rep/prac10
        ports:
        - containerPort: 3000 
       